// import { v4 as uuid } from "uuid";
const date = new Date().toISOString();


const lighthouses = [
  {
    name: 'Achillbeg',
    latitude: 53.85875,
    longitude: -9.94689,
    abovewater: 56,
    towerheight: 9,
    range_w: 16,
    range_r: 11,
    coast: "North Atlantic Ocean",
    constructed: '1965-01-01',
    currentdate: date,
    image_url: '/lighthouses/achillbeg.jpg',
    country: "Ireland"
  },
  {
    name: 'Ardnakinna',
    latitude: 55.01525,
    longitude: -8.56000,
    abovewater: 62,
    towerheight: 20,
    range_w: 14,
    range_r: 9,
    coast: "North Atlantic Ocean",
    constructed: '1850-01-01',
    currentdate: date,
    image_url: '/lighthouses/ardnakinna.jpg',
    country: "Ireland"
  },
  {
    name: 'Aranmore',
    latitude: 54.9956698,
    longitude: -8.5689206,
    abovewater: 71,
    towerheight: 23,
    range_w: 18,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: '1859-01-01',
    currentdate: date,
    image_url: '/lighthouses/aranmore.jpg',
    country: "Ireland"
  },
  {
    name: 'Baily',
    latitude: 53.36108,
    longitude: -6.05086,
    abovewater: 41,
    towerheight: 13,
    range_w: 18,
    range_r: 0,
    coast: "Irish Sea",
    constructed: '1814-01-01',
    currentdate: date,
    image_url: '/lighthouses/baily.jpg',
    country: "Ireland"
  },
  {
    name: 'Ballagh Rock',
    latitude: 55.00000,
    longitude: -8.48000,
    abovewater: 13,
    towerheight: 10,
    range_w: 5,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: '1875-01-01',
    currentdate: date,
    image_url: '/lighthouses/ballagh rocks.jpg',
    country: "Ireland"
  },
  {
    name: 'Ballinacourty',
    latitude: 52.07817,
    longitude: -7.55194,
    abovewater: 16,
    towerheight: 13,
    range_w: 10,
    range_r: 8,
    coast: "Celtic Sea",
    constructed: '1858-01-01',
    currentdate: date,
    image_url: '/lighthouses/ballinacourty.jpg',
    country: "Ireland"
  },
  {
    name: 'Ballycotton',
    latitude: 51.82583,
    longitude: -7.98528,
    abovewater: 59,
    towerheight: 15,
    range_w: 18,
    range_r: 14,
    coast:"Celtic Sea",
    constructed: '1848-01-01',
    currentdate: date,
    image_url: '/lighthouses/ballycotton.jpg',
    country: "Ireland"
  },
  {
    name: 'Barr Point Fog Signal',
    latitude: 54.85875,
    longitude: -5.77833,
    abovewater: 0,
    towerheight: 0,
    range_w: 0,
    range_r: 0,
    coast: "North Channel",
    constructed: '1905-01-01',
    currentdate: date,
    image_url: '/lighthouses/barr-point.png',
    country: "Northern Ireland"
  },
  {
    name: 'Blackhead (Antrim)',
    latitude: 54.76667,
    longitude: -5.68528,
    abovewater: 45,
    towerheight: 16,
    range_w: 27,
    range_r: 0,
    coast: "North Channel",
    constructed: '1902-01-01',
    currentdate: date,
    image_url: '/lighthouses/blackhead (antrim).jpg',
    country: "Northern Ireland"
  },
  {
    name: 'Blackhead (Clare)',
    latitude: 53.15306,
    longitude: -9.26667,
    abovewater: 20,
    towerheight: 8,
    range_w: 11,
    range_r: 8,
    coast: "North Atlantic Ocean",
    constructed: '1936-01-01',
    currentdate: date,
    image_url: '/lighthouses/blackhead (clare).jpg',
    country: "Ireland"
  },
  {
    name: 'Blackhorse Rocks Beacon',
    latitude: 51.47395,
    longitude: -9.69472,
    abovewater: 9,
    towerheight: 9,
    range_w: 5,
    range_r: 0,
    coast:"North Atlantic Ocean",
    constructed: '1848-01-01',
    currentdate: date,
    image_url: '/lighthouses/Horse Rock beacon.jpg',
    country: "Ireland"
  },
  {
    name: 'Blackrock (Mayo)',
    latitude: 54.06917,
    longitude: -10.32056,
    abovewater: 86,
    towerheight: 15,
    range_w: 18,
    range_r: 14,
    coast: "North Atlantic Ocean",
    constructed: '1864-01-01',
    currentdate: date,
    image_url: '/lighthouses/blackrock (mayo).jpg',
    country: "Ireland"
  },
  {
    name: 'Blackrock (Sligo)',
    latitude: 54.30667,
    longitude: -8.61667,
    abovewater: 24,
    towerheight: 25,
    range_w: 10,
    range_r: 8,
    coast: "North Atlantic Ocean",
    constructed: '1819-01-01',
    currentdate: date,
    image_url: '/lighthouses/blackrock (sligo).jpg',
    country: "Ireland"
  },
  {
    name: 'Blacksod',
    latitude: 54.09972,
    longitude: -10.06000,
    abovewater: 13,
    towerheight: 12,
    range_w: 12,
    range_r: 9,
    coast: "North Atlantic Ocean",
    constructed: '1864-01-01',
    currentdate: date,
    image_url: '/lighthouses/blacksod.jpg',
    country: "Ireland"
  },
  {
    name: 'Broadhaven',
    latitude: 54.26667,
    longitude: -9.88806,
    abovewater: 27,
    towerheight: 15,
    range_w: 17,
    range_r: 12,
    coast: "North Atlantic Ocean",
    constructed: '1848-01-01',
    currentdate: date,
    image_url: '/lighthouses/broadhaven.jpg',
    country: "Ireland"
  },
  {
    name: 'Bull Rock',
    latitude: 51.59139,
    longitude: -10.30278,
    abovewater: 4,
    towerheight: 4,
    range_w: 18,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: '1888-01-01',
    currentdate: date,
    image_url: '/lighthouses/bull rock.jpg',
    country: "Ireland"
  },
  {
    name: 'Bull Rock Beacon',
    latitude: 51.47400,
    longitude: -9.69444,
    abovewater: 12,
    towerheight: 12,
    range_w: 4,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: '1999-01-01',
    currentdate: date,
    image_url: '/lighthouses/bull rock beacon.jpg',
    country: "Ireland"
  },
  {
    name: 'Buncrana',
    latitude: 55.1265883,
    longitude: -7.4669514,
    abovewater: 7,
    towerheight: 7,
    range_w: 13,
    range_r: 10,
    coast: "North Atlantic Ocean",
    constructed: '1876-01-01',
    currentdate: date,
    image_url: '/lighthouses/buncrana.jpg',
    country: "Ireland"
  },
  {
    name: 'Burren Rocks Beacon',
    latitude: 53.49175,
    longitude: -6.04067,
    abovewater: 7,
    towerheight: 7,
    range_w: 5,
    range_r: 0,
    coast: "Irish Sea",
    constructed: '2010-03-01',
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Cardy Rocks Beacon',
    latitude: 53.632,
    longitude: -6.181,
    abovewater: 6,
    towerheight: 6,
    range_w: 4,
    range_r: 0,
    coast: "Irish Sea",
    constructed: '2021-09-01',
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Cashla Bay',
    latitude: 53.26306,
    longitude: -9.56583,
    abovewater: 6,
    towerheight: 4,
    range_w: 8,
    range_r: 6,
    coast: "North Atlantic Ocean",
    constructed: '1984-03-01',
    currentdate: date,
    image_url: '/lighthouses/Cashla Bay.jpg',
    country: "Ireland"
  },
  {
    name: 'Colt Rocks Beacon',
    latitude: 51.63447,
    longitude: -9.91812,
    abovewater: 7,
    towerheight: 7,
    range_w: 5,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: '2009-10-08',
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Copper Point',
    latitude: 51.50333,
    longitude: -9.53333,
    abovewater: 16,
    towerheight: 16,
    range_w: 8,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: '1864-01-01',
    currentdate: date,
    image_url: '/lighthouses/Copper-Point-PT.png',
    country: "Ireland"
  },
  {
    name: 'Corlis Point LLs',
    latitude: 52.62806,
    longitude: -9.58806,
    abovewater: 27,
    towerheight: 25,
    range_w: 10,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: '1998-09-20',
    currentdate: date,
    image_url: '/lighthouses/Corlis Point.jpg',
    country: "Ireland"
  },
  {
    name: 'Cromwell Point',
    latitude: 51.93333,
    longitude: -10.32306,
    abovewater: 16,
    towerheight: 15,
    range_w: 17,
    range_r: 15,
    coast: "North Atlantic Ocean",
    constructed: '1841-02-01',
    currentdate: date,
    image_url: '/lighthouses/Cromwell Point.jpg',
    country: "Ireland"
  },
  {
    name: 'Crookhaven',
    latitude: 51.47722,
    longitude: -9.70389,
    abovewater: 20,
    towerheight: 14,
    range_w: 13,
    range_r: 11,
    coast: "North Atlantic Ocean",
    constructed: '1838-10-31',
    currentdate: date,
    image_url: '/lighthouses/Crookhaven.jpg',
    country: "Ireland"
  },
  {
    name: 'Donaghadee',
    latitude: 54.64528,
    longitude: -5.53028,
    abovewater: 17,
    towerheight: 16,
    range_w: 17,
    range_r: 13,
    coast: "North Channel",
    constructed: '1836-01-01',
    currentdate: date,
    image_url: '/lighthouses/Donaghadee.jpg',
    country: "Northern Ireland"
  },
  {
    name: 'Dunmore East',
    latitude: 52.14972,
    longitude: -6.98806,
    abovewater: 13,
    towerheight: 16,
    range_w: 16,
    range_r: 13,
    coast: "Celtic Sea",
    constructed: '1825-01-01',
    currentdate: date,
    image_url: '/lighthouses/Dunmore East.jpg',
    country: "Ireland"
  },
  {
    name: 'Dunree',
    latitude: 55.19708,
    longitude: -7.55708,
    abovewater: 46,
    towerheight: 6,
    range_w: 12,
    range_r: 9,
    coast: "North Atlantic Ocean",
    constructed: '1875-01-01',
    currentdate: date,
    image_url: '/lighthouses/Dunree.png',
    country: "Ireland"
  },
  {
    name: 'Eagle Island',
    latitude: 54.28333,
    longitude: -10.09167,
    abovewater: 67,
    towerheight: 11,
    range_w: 18,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Eeragh',
    latitude: 53.14806,
    longitude: -9.85722,
    abovewater: 35,
    towerheight: 31,
    range_w: 18,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Fanad Head',
    latitude: 55.27778,
    longitude: -7.63306,
    abovewater: 39,
    towerheight: 22,
    range_w: 18,
    range_r: 14,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Fastnet',
    latitude: 51.38833,
    longitude: -9.60278,
    abovewater: 55,
    towerheight: 54,
    range_w: 18,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Ferris Point',
    latitude: 54.85194,
    longitude: -5.78861,
    abovewater: 18,
    towerheight: 16,
    range_w: 10,
    range_r: 0,
    coast: "North Channel",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Northern Ireland"
  },
  {
    name: 'Galley Head',
    latitude: 51.52806,
    longitude: -8.95194,
    abovewater: 53,
    towerheight: 21,
    range_w: 23,
    range_r: 0,
    coast: "Celtic Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Green Island',
    latitude: 54.03333,
    longitude: -6.09472,
    abovewater: 13,
    towerheight: 1,
    range_w: 11,
    range_r: 0,
    coast: "Irish Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Harbour Rock Beacon',
    latitude: 51.93167,
    longitude: -10.31167,
    abovewater: 12,
    towerheight: 12,
    range_w: 5,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Haulbowline',
    latitude: 54.02028,
    longitude: -6.07806,
    abovewater: 32,
    towerheight: 34,
    range_w: 10,
    range_r: 0,
    coast: "Irish Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Hook Head',
    latitude: 52.12306,
    longitude: -6.92694,
    abovewater: 46,
    towerheight: 35,
    range_w: 18,
    range_r: 0,
    coast: "Celtic Sea",
    constructed: '1172-01-01',
    currentdate: date,
    image_url: '/lighthouses/hook.jpg',
    country: "Ireland"
  },
  {
    name: 'Inisheer',
    latitude: 53.04722,
    longitude: -9.52306,
    abovewater: 34,
    towerheight: 34,
    range_w: 16,
    range_r: 11,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Inishgort',
    latitude: 53.82667,
    longitude: -9.66722,
    abovewater: 11,
    towerheight: 8,
    range_w: 10,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Inishowen',
    latitude: 55.22667,
    longitude: -6.92639,
    abovewater: 29,
    towerheight: 23,
    range_w: 18,
    range_r: 14,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Inishtearaght',
    latitude: 52.07583,
    longitude: -10.66194,
    abovewater: 84,
    towerheight: 17,
    range_w: 18,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Inishtrahull',
    latitude: 55.43083,
    longitude: -7.24333,
    abovewater: 59,
    towerheight: 23,
    range_w: 18,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Kish',
    latitude: 53.31083,
    longitude: -5.92667,
    abovewater: 31,
    towerheight: 29,
    range_w: 22,
    range_r: 0,
    coast: "Irish Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Loop Head',
    latitude: 52.56194,
    longitude: -9.93139,
    abovewater: 84,
    towerheight: 23,
    range_w: 23,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/loop.png',
    country: "Ireland"
  },
  {
    name: 'Maidens',
    latitude: 54.92806,
    longitude: -5.72667,
    abovewater: 29,
    towerheight: 23,
    range_w: 18,
    range_r: 0,
    coast: "North Channel",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Northern Ireland"
  },
  {
    name: 'Mew Island',
    latitude: 54.69861,
    longitude: -5.51194,
    abovewater: 37,
    towerheight: 37,
    range_w: 18,
    range_r: 0,
    coast: "North Channel",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Northern Ireland"
  },
  {
    name: 'Mine Head',
    latitude: 51.99333,
    longitude: -7.58611,
    abovewater: 87,
    towerheight: 21,
    range_w: 12,
    range_r: 0,
    coast: "Celtic Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Mizen Head',
    latitude: 51.44806,
    longitude: -9.82056,
    abovewater: 55,
    towerheight: 2,
    range_w: 12,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Muglins',
    latitude: 53.27472,
    longitude: -6.07500,
    abovewater: 14,
    towerheight: 14,
    range_w: 11,
    range_r: 0,
    coast: "Irish Sea",
    constructed: '1880-01-01',
    currentdate: date,
    image_url: '/lighthouses/muglins.jpg',
    country: "Ireland"
    },
  {
    name: 'Old Head of Kinsale',
    latitude: 51.60583,
    longitude: -8.53222,
    abovewater: 72,
    towerheight: 30,
    range_w: 20,
    range_r: 0,
    coast: "Celtic Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: "Rathlin O'Birne",
    latitude: 54.66444,
    longitude: -8.83306,
    abovewater: 74,
    towerheight: 27,
    range_w: 12,
    range_r: 10,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Rathlin East',
    latitude: 55.30222,
    longitude: -6.17056,
    abovewater: 74,
    towerheight: 27,
    range_w: 18,
    range_r: 0,
    coast: "North Channel",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Northern Ireland"
  },
  {
    name: 'Rathlin West',
    latitude: 55.30222,
    longitude: -6.27806,
    abovewater: 62,
    towerheight: 18,
    range_w: 18,
    range_r: 0,
    coast: "North Channel",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Northern Ireland"
  },
  {
    name: 'Roancarrigmore',
    latitude: 51.65139,
    longitude: -9.74611,
    abovewater: 13,
    towerheight: 7,
    range_w: 11,
    range_r: 9,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Roches Point',
    latitude: 51.79333,
    longitude: -8.24194,
    abovewater: 30,
    towerheight: 14,
    range_w: 18,
    range_r: 12,
    coast: "Celtic Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Rockabill',
    latitude: 53.59722,
    longitude: -6.08694,
    abovewater: 45,
    towerheight: 32,
    range_w: 18,
    range_r: 14,
    coast: "Irish Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Rotten Island',
    latitude: 54.61417,
    longitude: -8.44083,
    abovewater: 20,
    towerheight: 14,
    range_w: 15,
    range_r: 11,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Rue Point',
    latitude: 55.25861,
    longitude: -6.18861,
    abovewater: 16,
    towerheight: 11,
    range_w: 14,
    range_r: 0,
    coast: "North Channel",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Northern Ireland"
  },
  {
    name: 'Slyne Head',
    latitude: 53.40000,
    longitude: -10.23333,
    abovewater: 35,
    towerheight: 24,
    range_w: 19,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'St Johns Point (Donegal)',
    latitude: 54.57056,
    longitude: -8.46000,
    abovewater: 30,
    towerheight: 14,
    range_w: 14,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: "St John's Point (Down)",
    latitude: 54.22694,
    longitude: -5.65833,
    abovewater: 40,
    towerheight: 37,
    range_w: 25,
    range_r: 0,
    coast: "Irish Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Northern Ireland"
  },
  {
    name: 'Sheeps Head',
    latitude: 51.54083,
    longitude: -9.45500,
    abovewater: 83,
    towerheight: 7,
    range_w: 15,
    range_r: 9,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Skelligs',
    latitude: 51.73694,
    longitude: -10.54083,
    abovewater: 53,
    towerheight: 12,
    range_w: 12,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Straw Island',
    latitude: 53.11667,
    longitude: -9.63333,
    abovewater: 11,
    towerheight: 11,
    range_w: 12,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Tory Island',
    latitude: 55.27333,
    longitude: -8.24083,
    abovewater: 40,
    towerheight: 27,
    range_w: 18,
    range_r: 0,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Tuskar',
    latitude: 52.20389,
    longitude: -6.20722,
    abovewater: 34,
    towerheight: 33,
    range_w: 18,
    range_r: 0,
    coast: "Irish Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Valentia Directional Light',
    latitude: 51.92639,
    longitude: -10.30583,
    abovewater: 25,
    towerheight: 2,
    range_w: 11,
    range_r: 8,
    coast: "North Atlantic Ocean",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Vidal Bank',
    latitude: 54.03000,
    longitude: -6.09444,
    abovewater: 7,
    towerheight: 1,
    range_w: 11,
    range_r: 0,
    coast: "Irish Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  },
  {
    name: 'Wicklow Head',
    latitude: 52.96639,
    longitude: -6.00694,
    abovewater: 37,
    towerheight: 14,
    range_w: 18,
    range_r: 0,
    coast: "Irish Sea",
    constructed: date,
    currentdate: date,
    image_url: '/lighthouses/placeholder-image.jpg',
    country: "Ireland"
  }
]

export {lighthouses};
